version: "3.9"

volumes:
  pg-data:

services:
  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5431:5432"
    env_file:
      - ./.env
    volumes:
      - pg-data:/var/lib/postgresql/data